// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: draftspecs/messagingspec/messagetypes.proto

package messagingspec

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MessageTypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ApplicationKey is the identity key of the application to query.
	ApplicationKey string `protobuf:"bytes,1,opt,name=application_key,json=applicationKey,proto3" json:"application_key,omitempty"`
}

func (x *MessageTypesRequest) Reset() {
	*x = MessageTypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draftspecs_messagingspec_messagetypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTypesRequest) ProtoMessage() {}

func (x *MessageTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draftspecs_messagingspec_messagetypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTypesRequest.ProtoReflect.Descriptor instead.
func (*MessageTypesRequest) Descriptor() ([]byte, []int) {
	return file_draftspecs_messagingspec_messagetypes_proto_rawDescGZIP(), []int{0}
}

func (x *MessageTypesRequest) GetApplicationKey() string {
	if x != nil {
		return x.ApplicationKey
	}
	return ""
}

type MessageTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// MessageTypes is the set of messages supported by the server.
	MessageTypes []*MessageType `protobuf:"bytes,1,rep,name=message_types,json=messageTypes,proto3" json:"message_types,omitempty"`
}

func (x *MessageTypesResponse) Reset() {
	*x = MessageTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draftspecs_messagingspec_messagetypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTypesResponse) ProtoMessage() {}

func (x *MessageTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draftspecs_messagingspec_messagetypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTypesResponse.ProtoReflect.Descriptor instead.
func (*MessageTypesResponse) Descriptor() ([]byte, []int) {
	return file_draftspecs_messagingspec_messagetypes_proto_rawDescGZIP(), []int{1}
}

func (x *MessageTypesResponse) GetMessageTypes() []*MessageType {
	if x != nil {
		return x.MessageTypes
	}
	return nil
}

type MessageType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// PortableName is the unique name used to identify messages of this type.
	PortableName string `protobuf:"bytes,1,opt,name=portable_name,json=portableName,proto3" json:"portable_name,omitempty"`
	// ConfigName is the name used to identify this message type in the
	// dogma.config.v1 API.
	//
	// This name may differ across builds, as it is based on the fully-qualified
	// Go type name.
	ConfigName string `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	// MediaTypes is a list of MIME media-types that the server may use to
	// represent messages of this type.
	MediaTypes []string `protobuf:"bytes,3,rep,name=media_types,json=mediaTypes,proto3" json:"media_types,omitempty"`
}

func (x *MessageType) Reset() {
	*x = MessageType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_draftspecs_messagingspec_messagetypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageType) ProtoMessage() {}

func (x *MessageType) ProtoReflect() protoreflect.Message {
	mi := &file_draftspecs_messagingspec_messagetypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageType.ProtoReflect.Descriptor instead.
func (*MessageType) Descriptor() ([]byte, []int) {
	return file_draftspecs_messagingspec_messagetypes_proto_rawDescGZIP(), []int{2}
}

func (x *MessageType) GetPortableName() string {
	if x != nil {
		return x.PortableName
	}
	return ""
}

func (x *MessageType) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *MessageType) GetMediaTypes() []string {
	if x != nil {
		return x.MediaTypes
	}
	return nil
}

var File_draftspecs_messagingspec_messagetypes_proto protoreflect.FileDescriptor

var file_draftspecs_messagingspec_messagetypes_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x64, 0x72, 0x61, 0x66, 0x74, 0x73, 0x70, 0x65, 0x63, 0x73, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64,
	0x6f, 0x67, 0x6d, 0x61, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x76,
	0x31, 0x22, 0x3e, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x22, 0x5c, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x64, 0x6f, 0x67, 0x6d, 0x61, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22,
	0x74, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x69, 0x6e, 0x66,
	0x69, 0x78, 0x2f, 0x64, 0x72, 0x61, 0x66, 0x74, 0x73, 0x70, 0x65, 0x63, 0x73, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x73, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_draftspecs_messagingspec_messagetypes_proto_rawDescOnce sync.Once
	file_draftspecs_messagingspec_messagetypes_proto_rawDescData = file_draftspecs_messagingspec_messagetypes_proto_rawDesc
)

func file_draftspecs_messagingspec_messagetypes_proto_rawDescGZIP() []byte {
	file_draftspecs_messagingspec_messagetypes_proto_rawDescOnce.Do(func() {
		file_draftspecs_messagingspec_messagetypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_draftspecs_messagingspec_messagetypes_proto_rawDescData)
	})
	return file_draftspecs_messagingspec_messagetypes_proto_rawDescData
}

var file_draftspecs_messagingspec_messagetypes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_draftspecs_messagingspec_messagetypes_proto_goTypes = []interface{}{
	(*MessageTypesRequest)(nil),  // 0: dogma.messaging.v1.MessageTypesRequest
	(*MessageTypesResponse)(nil), // 1: dogma.messaging.v1.MessageTypesResponse
	(*MessageType)(nil),          // 2: dogma.messaging.v1.MessageType
}
var file_draftspecs_messagingspec_messagetypes_proto_depIdxs = []int32{
	2, // 0: dogma.messaging.v1.MessageTypesResponse.message_types:type_name -> dogma.messaging.v1.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_draftspecs_messagingspec_messagetypes_proto_init() }
func file_draftspecs_messagingspec_messagetypes_proto_init() {
	if File_draftspecs_messagingspec_messagetypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_draftspecs_messagingspec_messagetypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageTypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draftspecs_messagingspec_messagetypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_draftspecs_messagingspec_messagetypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_draftspecs_messagingspec_messagetypes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draftspecs_messagingspec_messagetypes_proto_goTypes,
		DependencyIndexes: file_draftspecs_messagingspec_messagetypes_proto_depIdxs,
		MessageInfos:      file_draftspecs_messagingspec_messagetypes_proto_msgTypes,
	}.Build()
	File_draftspecs_messagingspec_messagetypes_proto = out.File
	file_draftspecs_messagingspec_messagetypes_proto_rawDesc = nil
	file_draftspecs_messagingspec_messagetypes_proto_goTypes = nil
	file_draftspecs_messagingspec_messagetypes_proto_depIdxs = nil
}
