// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/internal/pb/application.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Application describes the message types for a specific application.
type Application struct {
	// Identity is the identity of the application.
	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Commands is a list of media-types for commands that are consumed by the
	// application.
	Commands []string `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	// Events is a list of media-types for events that are produced by the
	// application.
	Events               []string `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_734ddd8f0bad4aa7, []int{0}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Application) GetCommands() []string {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *Application) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Application)(nil), "dogma.api.messaging.v1.Application")
}

func init() { proto.RegisterFile("api/internal/pb/application.proto", fileDescriptor_734ddd8f0bad4aa7) }

var fileDescriptor_734ddd8f0bad4aa7 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xb1, 0x4f, 0x87, 0x30,
	0x10, 0x85, 0x83, 0x24, 0x04, 0xcb, 0xd6, 0x81, 0x10, 0x06, 0x83, 0x4e, 0x18, 0x93, 0x36, 0xea,
	0xea, 0xa2, 0x9b, 0x2b, 0xa3, 0xdb, 0x01, 0xb5, 0x5e, 0x42, 0xaf, 0x95, 0x9e, 0x44, 0x27, 0xff,
	0x75, 0x13, 0x44, 0x4c, 0xc8, 0x6f, 0x7c, 0xb9, 0xf7, 0xbd, 0xfb, 0xc4, 0x25, 0x04, 0xd4, 0x48,
	0x6c, 0x66, 0x82, 0x49, 0x87, 0x5e, 0x43, 0x08, 0x13, 0x0e, 0xc0, 0xe8, 0x49, 0x85, 0xd9, 0xb3,
	0x97, 0xe5, 0xe8, 0xad, 0x03, 0x05, 0x01, 0x95, 0x33, 0x31, 0x82, 0x45, 0xb2, 0x6a, 0xb9, 0xad,
	0x2f, 0x8e, 0x28, 0x8e, 0x86, 0x18, 0xf9, 0xeb, 0x97, 0xbb, 0xfa, 0x16, 0xc5, 0xe3, 0xff, 0x98,
	0x7c, 0x10, 0xf9, 0x5f, 0xa1, 0x4a, 0x9a, 0xa4, 0x2d, 0xee, 0x1a, 0x75, 0x7a, 0x59, 0x3d, 0x6f,
	0xbd, 0x6e, 0x27, 0x64, 0x2d, 0xf2, 0xc1, 0x3b, 0x07, 0x34, 0xc6, 0xea, 0xac, 0x49, 0xdb, 0xf3,
	0x6e, 0xcf, 0xb2, 0x14, 0x99, 0x59, 0x0c, 0x71, 0xac, 0xd2, 0xf5, 0xb2, 0xa5, 0xa7, 0x9b, 0x97,
	0x6b, 0x8b, 0xfc, 0xf6, 0xd1, 0xab, 0xc1, 0x3b, 0xbd, 0xfe, 0x62, 0x7c, 0xd7, 0x48, 0xaf, 0xf8,
	0xa9, 0x0f, 0xf2, 0x7d, 0xb6, 0x4a, 0xdf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x3f, 0x57,
	0x66, 0x11, 0x01, 0x00, 0x00,
}
