// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/internal/pb/message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MessageSource describes the source of a message.
type MessageSource struct {
	App                  *Identity `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	Handler              *Identity `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`
	InstanceId           string    `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MessageSource) Reset()         { *m = MessageSource{} }
func (m *MessageSource) String() string { return proto.CompactTextString(m) }
func (*MessageSource) ProtoMessage()    {}
func (*MessageSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7c7c952ed9e0f9, []int{0}
}

func (m *MessageSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSource.Unmarshal(m, b)
}
func (m *MessageSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSource.Marshal(b, m, deterministic)
}
func (m *MessageSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSource.Merge(m, src)
}
func (m *MessageSource) XXX_Size() int {
	return xxx_messageInfo_MessageSource.Size(m)
}
func (m *MessageSource) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSource.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSource proto.InternalMessageInfo

func (m *MessageSource) GetApp() *Identity {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *MessageSource) GetHandler() *Identity {
	if m != nil {
		return m.Handler
	}
	return nil
}

func (m *MessageSource) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

// MessageMetaData contains meta-data about a message.
type MessageMetaData struct {
	MessageId            string         `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CausationId          string         `protobuf:"bytes,2,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        string         `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Source               *MessageSource `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt            string         `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledFor         string         `protobuf:"bytes,6,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageMetaData) Reset()         { *m = MessageMetaData{} }
func (m *MessageMetaData) String() string { return proto.CompactTextString(m) }
func (*MessageMetaData) ProtoMessage()    {}
func (*MessageMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7c7c952ed9e0f9, []int{1}
}

func (m *MessageMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageMetaData.Unmarshal(m, b)
}
func (m *MessageMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageMetaData.Marshal(b, m, deterministic)
}
func (m *MessageMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageMetaData.Merge(m, src)
}
func (m *MessageMetaData) XXX_Size() int {
	return xxx_messageInfo_MessageMetaData.Size(m)
}
func (m *MessageMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageMetaData proto.InternalMessageInfo

func (m *MessageMetaData) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *MessageMetaData) GetCausationId() string {
	if m != nil {
		return m.CausationId
	}
	return ""
}

func (m *MessageMetaData) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *MessageMetaData) GetSource() *MessageSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MessageMetaData) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MessageMetaData) GetScheduledFor() string {
	if m != nil {
		return m.ScheduledFor
	}
	return ""
}

// MessageEnvelope is a container for a message and its meta-data.
type MessageEnvelope struct {
	MetaData             *MessageMetaData `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	Packet               *Packet          `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MessageEnvelope) Reset()         { *m = MessageEnvelope{} }
func (m *MessageEnvelope) String() string { return proto.CompactTextString(m) }
func (*MessageEnvelope) ProtoMessage()    {}
func (*MessageEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7c7c952ed9e0f9, []int{2}
}

func (m *MessageEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageEnvelope.Unmarshal(m, b)
}
func (m *MessageEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageEnvelope.Marshal(b, m, deterministic)
}
func (m *MessageEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageEnvelope.Merge(m, src)
}
func (m *MessageEnvelope) XXX_Size() int {
	return xxx_messageInfo_MessageEnvelope.Size(m)
}
func (m *MessageEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_MessageEnvelope proto.InternalMessageInfo

func (m *MessageEnvelope) GetMetaData() *MessageMetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *MessageEnvelope) GetPacket() *Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageSource)(nil), "dogma.api.messaging.v1.MessageSource")
	proto.RegisterType((*MessageMetaData)(nil), "dogma.api.messaging.v1.MessageMetaData")
	proto.RegisterType((*MessageEnvelope)(nil), "dogma.api.messaging.v1.MessageEnvelope")
}

func init() { proto.RegisterFile("api/internal/pb/message.proto", fileDescriptor_8f7c7c952ed9e0f9) }

var fileDescriptor_8f7c7c952ed9e0f9 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x8b, 0xd4, 0x30,
	0x14, 0x85, 0xa9, 0xab, 0xa3, 0x4d, 0x77, 0x14, 0xf2, 0x20, 0xc3, 0xe2, 0xae, 0xe3, 0xc8, 0xe2,
	0x8a, 0xd0, 0x62, 0x05, 0x1f, 0x04, 0x1f, 0x94, 0x55, 0xe8, 0xc3, 0x82, 0xd4, 0x37, 0x5f, 0xca,
	0x9d, 0xe4, 0x6e, 0x27, 0xd8, 0x26, 0x31, 0xbd, 0x5d, 0xf4, 0x57, 0xf8, 0x17, 0xfc, 0xa3, 0x82,
	0x34, 0x4d, 0x47, 0x1d, 0x1c, 0xdc, 0xd7, 0x93, 0x73, 0x72, 0xef, 0xf9, 0xb8, 0xec, 0x18, 0xac,
	0xca, 0x94, 0x26, 0x74, 0x1a, 0x9a, 0xcc, 0xae, 0xb3, 0x16, 0xbb, 0x0e, 0x6a, 0x4c, 0xad, 0x33,
	0x64, 0xf8, 0x7d, 0x69, 0xea, 0x16, 0x52, 0xb0, 0x2a, 0x1d, 0x1f, 0x94, 0xae, 0xd3, 0xab, 0xe7,
	0x47, 0x27, 0xbb, 0x31, 0x25, 0x51, 0x93, 0xa2, 0x6f, 0x63, 0xee, 0xe8, 0xc1, 0xee, 0xbb, 0x05,
	0xf1, 0x19, 0x69, 0x7c, 0x5d, 0xfd, 0x88, 0xd8, 0xfc, 0x62, 0x9c, 0xf3, 0xd1, 0xf4, 0x4e, 0x20,
	0xcf, 0xd9, 0x01, 0x58, 0xbb, 0xb8, 0xb9, 0x8c, 0xce, 0x92, 0x7c, 0x99, 0xfe, 0x7b, 0x6a, 0x5a,
	0x84, 0x21, 0xe5, 0x60, 0xe6, 0xaf, 0xd8, 0xed, 0x0d, 0x68, 0xd9, 0xa0, 0x5b, 0xdc, 0xba, 0x66,
	0x6e, 0x0a, 0xf0, 0x87, 0x2c, 0x51, 0xba, 0x23, 0xd0, 0x02, 0x2b, 0x25, 0x17, 0xb3, 0x65, 0x74,
	0x16, 0x97, 0x6c, 0x92, 0x0a, 0xb9, 0xfa, 0x19, 0xb1, 0x7b, 0x61, 0xc5, 0x0b, 0x24, 0x38, 0x07,
	0x02, 0x7e, 0xcc, 0x58, 0xa0, 0x33, 0x64, 0x22, 0x9f, 0x89, 0x83, 0x52, 0x48, 0xfe, 0x88, 0x1d,
	0x0a, 0xe8, 0x3b, 0x20, 0x65, 0xf4, 0x60, 0xb8, 0xe1, 0x0d, 0xc9, 0x56, 0x2b, 0x24, 0x3f, 0x65,
	0x77, 0x85, 0x71, 0x0e, 0x9b, 0xad, 0xe9, 0xc0, 0x9b, 0xe6, 0x7f, 0xa8, 0x85, 0xe4, 0xaf, 0xd9,
	0xac, 0xf3, 0x5c, 0x02, 0x90, 0xd3, 0x7d, 0xc5, 0xfe, 0x82, 0x58, 0x86, 0xd0, 0xb0, 0xa7, 0x70,
	0x08, 0x84, 0xb2, 0x02, 0xf2, 0x6c, 0xe2, 0x32, 0x0e, 0xca, 0x1b, 0xe2, 0x8f, 0xd9, 0xbc, 0x13,
	0x1b, 0x94, 0x7d, 0x83, 0xb2, 0xba, 0x34, 0x2e, 0xb4, 0x3f, 0xdc, 0x8a, 0xef, 0x8d, 0x5b, 0x7d,
	0xff, 0xdd, 0xff, 0x9d, 0xbe, 0xc2, 0xc6, 0x58, 0xe4, 0xe7, 0x2c, 0x6e, 0x91, 0xa0, 0x92, 0x40,
	0xe0, 0xeb, 0x27, 0xf9, 0x93, 0xff, 0x6c, 0x36, 0xb1, 0x2b, 0xef, 0xb4, 0x13, 0xc5, 0x97, 0x6c,
	0x36, 0x1e, 0x83, 0x07, 0x94, 0xe4, 0x27, 0xfb, 0xbe, 0xf8, 0xe0, 0x5d, 0x65, 0x70, 0xbf, 0x7d,
	0xf6, 0xe9, 0x69, 0xad, 0x68, 0xd3, 0xaf, 0x53, 0x61, 0xda, 0xcc, 0x67, 0x48, 0x7d, 0xc9, 0x94,
	0xbe, 0x54, 0x5f, 0xb3, 0x9d, 0x73, 0x5b, 0xcf, 0xfc, 0xa1, 0xbd, 0xf8, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xe5, 0xe6, 0x88, 0x64, 0xdf, 0x02, 0x00, 0x00,
}
