// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/internal/pb/routing.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DiscoverRoutesRequest is the request to a Routing.DiscoverRoutes() RPC.
type DiscoverRoutesRequest struct {
	// Commands is a list of protocol-names for foreign commands that are produced
	// by the caller for which the destination application is unknown.
	Commands []string `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	// Events is a list of protocol-names for foreign events that are consumed by
	// the caller for which the source application is unknown.
	Events               []string `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverRoutesRequest) Reset()         { *m = DiscoverRoutesRequest{} }
func (m *DiscoverRoutesRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoverRoutesRequest) ProtoMessage()    {}
func (*DiscoverRoutesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d2d14d3eb1de37b, []int{0}
}

func (m *DiscoverRoutesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverRoutesRequest.Unmarshal(m, b)
}
func (m *DiscoverRoutesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverRoutesRequest.Marshal(b, m, deterministic)
}
func (m *DiscoverRoutesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverRoutesRequest.Merge(m, src)
}
func (m *DiscoverRoutesRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoverRoutesRequest.Size(m)
}
func (m *DiscoverRoutesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverRoutesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverRoutesRequest proto.InternalMessageInfo

func (m *DiscoverRoutesRequest) GetCommands() []string {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *DiscoverRoutesRequest) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

// DiscoverRoutesResponse is the response from a Routing.DiscoverRoutes() RPC.
type DiscoverRoutesResponse struct {
	// Routes is a list of routes to applications that (at least partially)
	// satisfy the routing requirements of the caller.
	Routes               []*ApplicationRoute `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DiscoverRoutesResponse) Reset()         { *m = DiscoverRoutesResponse{} }
func (m *DiscoverRoutesResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoverRoutesResponse) ProtoMessage()    {}
func (*DiscoverRoutesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d2d14d3eb1de37b, []int{1}
}

func (m *DiscoverRoutesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverRoutesResponse.Unmarshal(m, b)
}
func (m *DiscoverRoutesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverRoutesResponse.Marshal(b, m, deterministic)
}
func (m *DiscoverRoutesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverRoutesResponse.Merge(m, src)
}
func (m *DiscoverRoutesResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoverRoutesResponse.Size(m)
}
func (m *DiscoverRoutesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverRoutesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverRoutesResponse proto.InternalMessageInfo

func (m *DiscoverRoutesResponse) GetRoutes() []*ApplicationRoute {
	if m != nil {
		return m.Routes
	}
	return nil
}

// ApplicationRoute describes the message types for a specific application as
// they relate to a DiscoverRoutesRequest.
type ApplicationRoute struct {
	// Application is the identity of the application.
	Application *Identity `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// Commands is a list of protocol-names for commands that are consumed by the
	// application. It is not an exhaustive list, only including those command
	// types that were specified in the original request.
	Commands []string `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	// Events is a list of protocol-names for events that are produced by the
	// application. It is not an exhaustive list, only including those event
	// types that were specified in the original request.
	Events               []string `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationRoute) Reset()         { *m = ApplicationRoute{} }
func (m *ApplicationRoute) String() string { return proto.CompactTextString(m) }
func (*ApplicationRoute) ProtoMessage()    {}
func (*ApplicationRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d2d14d3eb1de37b, []int{2}
}

func (m *ApplicationRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationRoute.Unmarshal(m, b)
}
func (m *ApplicationRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationRoute.Marshal(b, m, deterministic)
}
func (m *ApplicationRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationRoute.Merge(m, src)
}
func (m *ApplicationRoute) XXX_Size() int {
	return xxx_messageInfo_ApplicationRoute.Size(m)
}
func (m *ApplicationRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationRoute.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationRoute proto.InternalMessageInfo

func (m *ApplicationRoute) GetApplication() *Identity {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *ApplicationRoute) GetCommands() []string {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *ApplicationRoute) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*DiscoverRoutesRequest)(nil), "dogma.api.messaging.v1.DiscoverRoutesRequest")
	proto.RegisterType((*DiscoverRoutesResponse)(nil), "dogma.api.messaging.v1.DiscoverRoutesResponse")
	proto.RegisterType((*ApplicationRoute)(nil), "dogma.api.messaging.v1.ApplicationRoute")
}

func init() { proto.RegisterFile("api/internal/pb/routing.proto", fileDescriptor_4d2d14d3eb1de37b) }

var fileDescriptor_4d2d14d3eb1de37b = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x51, 0x4b, 0x84, 0x40,
	0x14, 0x85, 0x71, 0x17, 0xac, 0x46, 0x88, 0x18, 0x48, 0x44, 0x28, 0xc4, 0x27, 0x23, 0x9a, 0x21,
	0xfb, 0x03, 0xb5, 0xf4, 0x12, 0xbd, 0xcd, 0xe3, 0xbe, 0x8d, 0x3a, 0xd9, 0x85, 0x75, 0x66, 0xd6,
	0x19, 0xa5, 0xfa, 0x09, 0xfd, 0xea, 0x68, 0x94, 0xda, 0x95, 0x15, 0xf6, 0xf1, 0xde, 0xe3, 0x39,
	0xce, 0x77, 0x2e, 0xba, 0xe2, 0x1a, 0x28, 0x48, 0x2b, 0x5a, 0xc9, 0x37, 0x54, 0x17, 0xb4, 0x55,
	0x9d, 0x05, 0x59, 0x13, 0xdd, 0x2a, 0xab, 0x70, 0x58, 0xa9, 0xba, 0xe1, 0x84, 0x6b, 0x20, 0x8d,
	0x30, 0x86, 0xd7, 0xbf, 0x52, 0x7f, 0x1f, 0x5f, 0x4f, 0x6d, 0x50, 0x09, 0x69, 0xc1, 0x7e, 0x0e,
	0xbe, 0xf4, 0x15, 0x5d, 0x3e, 0x83, 0x29, 0x55, 0x2f, 0x5a, 0xa6, 0x3a, 0x2b, 0x0c, 0x13, 0xdb,
	0x4e, 0x18, 0x8b, 0x63, 0x74, 0x5a, 0xaa, 0xa6, 0xe1, 0xb2, 0x32, 0x91, 0x97, 0x2c, 0xb3, 0x33,
	0xf6, 0x37, 0xe3, 0x10, 0xf9, 0xa2, 0x17, 0xd2, 0x9a, 0x68, 0xe1, 0x94, 0x71, 0x4a, 0xd7, 0x28,
	0x9c, 0x86, 0x19, 0xad, 0xa4, 0x11, 0xf8, 0x11, 0xf9, 0xad, 0xdb, 0xb8, 0xac, 0x20, 0xcf, 0xc8,
	0xe1, 0xf7, 0x92, 0x27, 0xad, 0x37, 0x50, 0x72, 0x0b, 0x4a, 0xba, 0x08, 0x36, 0xfa, 0xd2, 0x6f,
	0x0f, 0x5d, 0x4c, 0x45, 0xbc, 0x42, 0x01, 0xff, 0xdf, 0x45, 0x5e, 0xe2, 0x65, 0x41, 0x9e, 0xcc,
	0x65, 0xbf, 0x8c, 0xe8, 0x6c, 0xd7, 0xb4, 0x07, 0xba, 0x98, 0x05, 0x5d, 0xee, 0x82, 0xe6, 0x5f,
	0xe8, 0x84, 0x0d, 0xf5, 0x63, 0x85, 0xce, 0xf7, 0x99, 0xf1, 0xdd, 0xdc, 0xff, 0x0f, 0x16, 0x1d,
	0x93, 0x63, 0x3f, 0x1f, 0xaa, 0x5c, 0xdd, 0xae, 0x6f, 0x6a, 0xb0, 0xef, 0x5d, 0x41, 0x4a, 0xd5,
	0x50, 0xe7, 0xb5, 0xb0, 0xa5, 0x20, 0xdf, 0xe0, 0x83, 0x4e, 0xae, 0x5d, 0xf8, 0xee, 0xca, 0x0f,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x63, 0x54, 0x39, 0x03, 0x3e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoutingClient is the client API for Routing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoutingClient interface {
	// DiscoverRoutes queries the server about the applications it hosts as they
	// relate to a specific set of foreign message types that the caller is
	// attempting to route.
	DiscoverRoutes(ctx context.Context, in *DiscoverRoutesRequest, opts ...grpc.CallOption) (*DiscoverRoutesResponse, error)
}

type routingClient struct {
	cc *grpc.ClientConn
}

func NewRoutingClient(cc *grpc.ClientConn) RoutingClient {
	return &routingClient{cc}
}

func (c *routingClient) DiscoverRoutes(ctx context.Context, in *DiscoverRoutesRequest, opts ...grpc.CallOption) (*DiscoverRoutesResponse, error) {
	out := new(DiscoverRoutesResponse)
	err := c.cc.Invoke(ctx, "/dogma.api.messaging.v1.Routing/DiscoverRoutes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServer is the server API for Routing service.
type RoutingServer interface {
	// DiscoverRoutes queries the server about the applications it hosts as they
	// relate to a specific set of foreign message types that the caller is
	// attempting to route.
	DiscoverRoutes(context.Context, *DiscoverRoutesRequest) (*DiscoverRoutesResponse, error)
}

// UnimplementedRoutingServer can be embedded to have forward compatible implementations.
type UnimplementedRoutingServer struct {
}

func (*UnimplementedRoutingServer) DiscoverRoutes(ctx context.Context, req *DiscoverRoutesRequest) (*DiscoverRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverRoutes not implemented")
}

func RegisterRoutingServer(s *grpc.Server, srv RoutingServer) {
	s.RegisterService(&_Routing_serviceDesc, srv)
}

func _Routing_DiscoverRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServer).DiscoverRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogma.api.messaging.v1.Routing/DiscoverRoutes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServer).DiscoverRoutes(ctx, req.(*DiscoverRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Routing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dogma.api.messaging.v1.Routing",
	HandlerType: (*RoutingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiscoverRoutes",
			Handler:    _Routing_DiscoverRoutes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/internal/pb/routing.proto",
}
