// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/internal/pb/types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Identity is a protocol buffers representation of the configkit.Identity type.
type Identity struct {
	// Name is the entity's unique name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key is the entity's immutable, unique key.
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_565b712cd72dd24a, []int{0}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Envelope is a protocol buffers representation of the envelope.Envelope type.
type Envelope struct {
	// MessageID is a unique identifier for the message.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// CausationID is the ID of the message that was being handled when the
	// message identified by MessageID was produced.
	CausationId string `protobuf:"bytes,2,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	// CorrelationID is the ID of the "root" message that entered the application
	// to cause the message identified by MessageID, either directly or
	// indirectly.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// SourceApplication is the identity of the Dogma application that produced
	// this message.
	SourceApplication *Identity `protobuf:"bytes,4,opt,name=source_application,json=sourceApplication,proto3" json:"source_application,omitempty"`
	// SourceHandler is the identity of the handler that produced the message. It
	// is the zero-value if the message was not produced by a handler.
	SourceHandler *Identity `protobuf:"bytes,5,opt,name=source_handler,json=sourceHandler,proto3" json:"source_handler,omitempty"`
	// SourceInstanceID is the aggregate or process instance that produced the
	// message. It is empty if the message was not produced by a handler, or it
	// was produced by an integration handler.
	SourceInstanceId string `protobuf:"bytes,6,opt,name=source_instance_id,json=sourceInstanceId,proto3" json:"source_instance_id,omitempty"`
	// CreatedAt is the time at which the message was created, marshaled in
	// RFC3339Nano format.
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ScheduledFor is the time at which a timeout message was scheduled,
	// marshaled in RFC3339Nano format.
	ScheduledFor string `protobuf:"bytes,8,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	// MessageMediaType is a MIME media-type describing the content and encoding
	// of the binary message data.
	MessageMediaType string `protobuf:"bytes,9,opt,name=message_media_type,json=messageMediaType,proto3" json:"message_media_type,omitempty"`
	// MessageData is the marshaled binary data representing the message.
	MessageData          []byte   `protobuf:"bytes,10,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_565b712cd72dd24a, []int{1}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Envelope) GetCausationId() string {
	if m != nil {
		return m.CausationId
	}
	return ""
}

func (m *Envelope) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *Envelope) GetSourceApplication() *Identity {
	if m != nil {
		return m.SourceApplication
	}
	return nil
}

func (m *Envelope) GetSourceHandler() *Identity {
	if m != nil {
		return m.SourceHandler
	}
	return nil
}

func (m *Envelope) GetSourceInstanceId() string {
	if m != nil {
		return m.SourceInstanceId
	}
	return ""
}

func (m *Envelope) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Envelope) GetScheduledFor() string {
	if m != nil {
		return m.ScheduledFor
	}
	return ""
}

func (m *Envelope) GetMessageMediaType() string {
	if m != nil {
		return m.MessageMediaType
	}
	return ""
}

func (m *Envelope) GetMessageData() []byte {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func init() {
	proto.RegisterType((*Identity)(nil), "dogma.messaging.v1.Identity")
	proto.RegisterType((*Envelope)(nil), "dogma.messaging.v1.Envelope")
}

func init() {
	proto.RegisterFile("api/internal/pb/types.proto", fileDescriptor_565b712cd72dd24a)
}

var fileDescriptor_565b712cd72dd24a = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x8b, 0xdb, 0x30,
	0x10, 0x86, 0x71, 0x93, 0xa6, 0x89, 0xf2, 0x41, 0xaa, 0x93, 0xa0, 0x2d, 0xa4, 0x29, 0x85, 0x94,
	0x16, 0xbb, 0x1f, 0xbf, 0x20, 0xfd, 0xa2, 0xa6, 0xf4, 0x12, 0x7a, 0xda, 0x8b, 0x99, 0x48, 0x13,
	0x47, 0xac, 0x2d, 0x69, 0x65, 0x39, 0xac, 0xff, 0xe1, 0xfe, 0xac, 0xc5, 0x92, 0xe3, 0x5d, 0x76,
	0x2f, 0x7b, 0x13, 0xcf, 0xbc, 0xef, 0x48, 0xf3, 0x6a, 0xc8, 0x2b, 0x30, 0x32, 0x91, 0xca, 0xa1,
	0x55, 0x50, 0x24, 0x66, 0x9f, 0xb8, 0xc6, 0x60, 0x15, 0x1b, 0xab, 0x9d, 0xa6, 0x54, 0xe8, 0xbc,
	0x84, 0xb8, 0xc4, 0xaa, 0x82, 0x5c, 0xaa, 0x3c, 0x3e, 0x7d, 0x59, 0x7f, 0x26, 0xe3, 0x54, 0xa0,
	0x72, 0xd2, 0x35, 0x94, 0x92, 0xa1, 0x82, 0x12, 0x59, 0xb4, 0x8a, 0x36, 0x93, 0x9d, 0x3f, 0xd3,
	0x25, 0x19, 0x5c, 0x62, 0xc3, 0x9e, 0x79, 0xd4, 0x1e, 0xd7, 0x37, 0x03, 0x32, 0xfe, 0xa5, 0x4e,
	0x58, 0x68, 0x83, 0xf4, 0x0d, 0x21, 0xa1, 0x1d, 0x66, 0x52, 0x74, 0xc6, 0x49, 0x47, 0x52, 0x41,
	0xdf, 0x92, 0x19, 0x87, 0xba, 0x02, 0x27, 0xb5, 0x6a, 0x05, 0xa1, 0xcd, 0xb4, 0x67, 0xa9, 0xa0,
	0xef, 0xc9, 0x82, 0x6b, 0x6b, 0xb1, 0xe8, 0x45, 0x03, 0x2f, 0x9a, 0xdf, 0xa3, 0xa9, 0xa0, 0x7f,
	0x09, 0xad, 0x74, 0x6d, 0x39, 0x66, 0x60, 0x4c, 0x21, 0xb9, 0xe7, 0x6c, 0xb8, 0x8a, 0x36, 0xd3,
	0xaf, 0xaf, 0xe3, 0xc7, 0x83, 0xc5, 0xe7, 0xa9, 0x76, 0x2f, 0x83, 0x6f, 0x7b, 0x67, 0xa3, 0x3f,
	0xc8, 0xa2, 0x6b, 0x76, 0x04, 0x25, 0x0a, 0xb4, 0xec, 0xf9, 0x13, 0x1a, 0xcd, 0x83, 0xe7, 0x4f,
	0xb0, 0xd0, 0x4f, 0xfd, 0x8b, 0xa4, 0xaa, 0x1c, 0x28, 0xee, 0x23, 0x18, 0xf9, 0xc7, 0x2f, 0x43,
	0x25, 0xed, 0x0a, 0xa9, 0x68, 0x83, 0xe2, 0x16, 0xc1, 0xa1, 0xc8, 0xc0, 0xb1, 0x17, 0x21, 0xa8,
	0x8e, 0x6c, 0x1d, 0x7d, 0x47, 0xe6, 0x15, 0x3f, 0xa2, 0xa8, 0x0b, 0x14, 0xd9, 0x41, 0x5b, 0x36,
	0xf6, 0x8a, 0x59, 0x0f, 0x7f, 0x6b, 0x7f, 0xe3, 0x39, 0xec, 0x12, 0x85, 0x84, 0xac, 0xfd, 0x5c,
	0x36, 0x09, 0x37, 0x76, 0x95, 0x7f, 0x6d, 0xe1, 0x7f, 0x63, 0xb0, 0xcd, 0xfe, 0xac, 0x16, 0xe0,
	0x80, 0x91, 0x55, 0xb4, 0x99, 0xed, 0xa6, 0x1d, 0xfb, 0x09, 0x0e, 0xbe, 0x7f, 0xbc, 0xf8, 0x90,
	0x4b, 0x77, 0xac, 0xf7, 0x31, 0xd7, 0x65, 0xe2, 0x67, 0x77, 0xf2, 0x2a, 0x91, 0xea, 0x20, 0xaf,
	0x93, 0x07, 0x9b, 0xb4, 0x1f, 0xf9, 0x25, 0xfa, 0x76, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x64,
	0x21, 0xb1, 0x63, 0x02, 0x00, 0x00,
}
