// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/draftspecs/messaging/pb/types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Identity is a protocol buffers representation of the configkit.Identity type.
type Identity struct {
	// Name is the entity's unique name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key is the entity's immutable, unique key.
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5342cbd07105874a, []int{0}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Source struct {
	// Application is the identity of the Dogma application that produced this
	// message.
	Application *Identity `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// Handler is the identity of the handler that produced the message. It is the
	// zero-value if the message was not produced by a handler.
	Handler *Identity `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	// InstanceID is the aggregate or process instance that produced the message.
	// It is empty if the message was not produced by a handler, or it was
	// produced by an integration handler.
	InstanceId           string   `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_5342cbd07105874a, []int{1}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetApplication() *Identity {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *Source) GetHandler() *Identity {
	if m != nil {
		return m.Handler
	}
	return nil
}

func (m *Source) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

// MetaData is a protocol buffers representation of the envelope.MetaData type.
type MetaData struct {
	// MessageID is a unique identifier for the message.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// CausationID is the ID of the message that was being handled when the
	// message identified by MessageID was produced.
	CausationId string `protobuf:"bytes,2,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	// CorrelationID is the ID of the "root" message that entered the application
	// to cause the message identified by MessageID, either directly or
	// indirectly.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Source describes the source of the message.
	Source *Source `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// CreatedAt is the time at which the message was created, marshaled in
	// binary format.
	CreatedAt []byte `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ScheduledFor is the time at which a timeout message was scheduled,
	// marshaled in binary format.
	ScheduledFor         []byte   `protobuf:"bytes,6,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaData) Reset()         { *m = MetaData{} }
func (m *MetaData) String() string { return proto.CompactTextString(m) }
func (*MetaData) ProtoMessage()    {}
func (*MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5342cbd07105874a, []int{2}
}

func (m *MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaData.Unmarshal(m, b)
}
func (m *MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaData.Marshal(b, m, deterministic)
}
func (m *MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaData.Merge(m, src)
}
func (m *MetaData) XXX_Size() int {
	return xxx_messageInfo_MetaData.Size(m)
}
func (m *MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MetaData proto.InternalMessageInfo

func (m *MetaData) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *MetaData) GetCausationId() string {
	if m != nil {
		return m.CausationId
	}
	return ""
}

func (m *MetaData) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *MetaData) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MetaData) GetCreatedAt() []byte {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *MetaData) GetScheduledFor() []byte {
	if m != nil {
		return m.ScheduledFor
	}
	return nil
}

// Envelope is a protocol buffers representation of the envelope.Envelope type.
type Envelope struct {
	// MetaData is the message meta-data.
	MetaData *MetaData `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	// Packet contains the binary representation of the message.
	Packet               *Packet  `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5342cbd07105874a, []int{3}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetMetaData() *MetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *Envelope) GetPacket() *Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

// Packet is a protocol buffers representation of the marshalkit.Packet type.
type Packet struct {
	// MediaType is a MIME media-type describing the content and encoding of the
	// binary data.
	MediaType string `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// Data is the marshaled binary data.
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_5342cbd07105874a, []int{4}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetMediaType() string {
	if m != nil {
		return m.MediaType
	}
	return ""
}

func (m *Packet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Identity)(nil), "dogma.messaging.v1.Identity")
	proto.RegisterType((*Source)(nil), "dogma.messaging.v1.Source")
	proto.RegisterType((*MetaData)(nil), "dogma.messaging.v1.MetaData")
	proto.RegisterType((*Envelope)(nil), "dogma.messaging.v1.Envelope")
	proto.RegisterType((*Packet)(nil), "dogma.messaging.v1.Packet")
}

func init() {
	proto.RegisterFile("internal/draftspecs/messaging/pb/types.proto", fileDescriptor_5342cbd07105874a)
}

var fileDescriptor_5342cbd07105874a = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4f, 0x8b, 0xd4, 0x4e,
	0x10, 0x25, 0xbb, 0xfb, 0xcb, 0x6f, 0xa6, 0x66, 0x56, 0xa4, 0x4f, 0x41, 0x14, 0xd7, 0x88, 0xb0,
	0x07, 0x49, 0x74, 0x04, 0xc1, 0x3f, 0x08, 0x8a, 0x0a, 0x39, 0x08, 0x12, 0x3d, 0x79, 0x09, 0x35,
	0xdd, 0x35, 0x33, 0xcd, 0x26, 0xdd, 0xb1, 0xbb, 0x66, 0x31, 0x1f, 0xc7, 0xcf, 0xe7, 0x97, 0x90,
	0x74, 0x92, 0x71, 0xc1, 0xc5, 0xbd, 0x15, 0x2f, 0xaf, 0xf2, 0x5e, 0xbd, 0x7e, 0xf0, 0x58, 0x1b,
	0x26, 0x67, 0xb0, 0xce, 0x95, 0xc3, 0x0d, 0xfb, 0x96, 0xa4, 0xcf, 0x1b, 0xf2, 0x1e, 0xb7, 0xda,
	0x6c, 0xf3, 0x76, 0x9d, 0x73, 0xd7, 0x92, 0xcf, 0x5a, 0x67, 0xd9, 0x0a, 0xa1, 0xec, 0xb6, 0xc1,
	0xec, 0xf0, 0x3d, 0xbb, 0x7c, 0x9a, 0x3e, 0x81, 0x59, 0xa1, 0xc8, 0xb0, 0xe6, 0x4e, 0x08, 0x38,
	0x31, 0xd8, 0x50, 0x12, 0x9d, 0x45, 0xe7, 0xf3, 0x32, 0xcc, 0xe2, 0x36, 0x1c, 0x5f, 0x50, 0x97,
	0x1c, 0x05, 0xa8, 0x1f, 0xd3, 0x9f, 0x11, 0xc4, 0x5f, 0xec, 0xde, 0x49, 0x12, 0x6f, 0x60, 0x81,
	0x6d, 0x5b, 0x6b, 0x89, 0xac, 0xad, 0x09, 0x7b, 0x8b, 0xd5, 0xdd, 0xec, 0x6f, 0x99, 0x6c, 0xd2,
	0x28, 0xaf, 0x2e, 0x88, 0xe7, 0xf0, 0xff, 0x0e, 0x8d, 0xaa, 0xc9, 0x05, 0x81, 0x9b, 0x76, 0x27,
	0xb2, 0xb8, 0x0f, 0x0b, 0x6d, 0x3c, 0xa3, 0x91, 0x54, 0x69, 0x95, 0x1c, 0x07, 0x73, 0x30, 0x41,
	0x85, 0x4a, 0x7f, 0x45, 0x30, 0xfb, 0x44, 0x8c, 0xef, 0x91, 0x51, 0xdc, 0x03, 0x18, 0xfe, 0x17,
	0xc8, 0xc3, 0x71, 0xf3, 0x11, 0x29, 0x94, 0x78, 0x00, 0x4b, 0x89, 0x7b, 0x1f, 0x1c, 0xf5, 0x84,
	0xe1, 0xd4, 0xc5, 0x01, 0x2b, 0x94, 0x78, 0x04, 0xb7, 0xa4, 0x75, 0x8e, 0xea, 0x03, 0x69, 0x90,
	0x3c, 0xbd, 0x82, 0x16, 0x4a, 0xac, 0x20, 0xf6, 0x21, 0x98, 0xe4, 0x24, 0x5c, 0x73, 0xe7, 0xba,
	0x6b, 0x86, 0xe8, 0xca, 0x91, 0xd9, 0x9b, 0x93, 0x8e, 0x90, 0x49, 0x55, 0xc8, 0xc9, 0x7f, 0x67,
	0xd1, 0xf9, 0xb2, 0x9c, 0x8f, 0xc8, 0x5b, 0x16, 0x0f, 0xe1, 0xd4, 0xcb, 0x1d, 0xa9, 0x7d, 0x4d,
	0xaa, 0xda, 0x58, 0x97, 0xc4, 0x81, 0xb1, 0x3c, 0x80, 0x1f, 0xad, 0x4b, 0x3b, 0x98, 0x7d, 0x30,
	0x97, 0x54, 0xdb, 0x96, 0xc4, 0x0b, 0x98, 0x37, 0xc4, 0x58, 0x29, 0x64, 0xfc, 0xd7, 0x83, 0x4c,
	0xe9, 0x94, 0xb3, 0x66, 0xca, 0x69, 0x05, 0x71, 0x8b, 0xf2, 0x82, 0x78, 0x7c, 0x8c, 0x6b, 0xed,
	0x7f, 0x0e, 0x8c, 0x72, 0x64, 0xa6, 0xaf, 0x20, 0x1e, 0x90, 0x21, 0x65, 0xa5, 0xb1, 0xea, 0x1b,
	0xf7, 0x27, 0x65, 0xa5, 0xf1, 0x6b, 0xd7, 0x52, 0xdf, 0xad, 0x60, 0xe9, 0x28, 0xf8, 0x0f, 0xf3,
	0xbb, 0xd7, 0xdf, 0x5e, 0x6e, 0x35, 0xef, 0xf6, 0xeb, 0x4c, 0xda, 0x26, 0x0f, 0x62, 0xac, 0xbf,
	0xe7, 0xda, 0x6c, 0xf4, 0x8f, 0xfc, 0xa6, 0x66, 0xaf, 0xe3, 0x50, 0xea, 0x67, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xec, 0x98, 0xb8, 0x16, 0x04, 0x03, 0x00, 0x00,
}
