// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: github.com/dogmatiq/verity/persistence/boltpersistence/internal/pb/process.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessInstance is a protocol buffers representation of
// persistence.ProcessInstance.
type ProcessInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInstance) Reset() {
	*x = ProcessInstance{}
	mi := &file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInstance) ProtoMessage() {}

func (x *ProcessInstance) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInstance.ProtoReflect.Descriptor instead.
func (*ProcessInstance) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInstance) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ProcessInstance) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ProcessInstance) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDesc = "" +
	"\n" +
	"Pgithub.com/dogmatiq/verity/persistence/boltpersistence/internal/pb/process.proto\x12\x1cverity.persistence.boltdb.v1\"`\n" +
	"\x0fProcessInstance\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04dataBDZBgithub.com/dogmatiq/verity/persistence/boltpersistence/internal/pbb\x06proto3"

var (
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDescData []byte
)

func file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDesc), len(file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDescData
}

var file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_goTypes = []any{
	(*ProcessInstance)(nil), // 0: verity.persistence.boltdb.v1.ProcessInstance
}
var file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_init()
}
func file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_init() {
	if File_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDesc), len(file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto = out.File
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_goTypes = nil
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_process_proto_depIdxs = nil
}
