// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: github.com/dogmatiq/verity/persistence/boltpersistence/internal/pb/queue.proto

package pb

import (
	envelopespec "github.com/dogmatiq/interopspec/envelopespec"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueueMessage is a protocol buffers representation of a
// persistence.QueueMessage.
type QueueMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	FailureCount  uint64                 `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	NextAttemptAt string                 `protobuf:"bytes,3,opt,name=next_attempt_at,json=nextAttemptAt,proto3" json:"next_attempt_at,omitempty"`
	Envelope      *envelopespec.Envelope `protobuf:"bytes,15,opt,name=Envelope,proto3" json:"Envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDescGZIP(), []int{0}
}

func (x *QueueMessage) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *QueueMessage) GetFailureCount() uint64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *QueueMessage) GetNextAttemptAt() string {
	if x != nil {
		return x.NextAttemptAt
	}
	return ""
}

func (x *QueueMessage) GetEnvelope() *envelopespec.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

var File_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDesc = "" +
	"\n" +
	"Ngithub.com/dogmatiq/verity/persistence/boltpersistence/internal/pb/queue.proto\x12\x1cverity.persistence.boltdb.v1\x1a;github.com/dogmatiq/interopspec/envelopespec/envelope.proto\"\xbe\x01\n" +
	"\fQueueMessage\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x04R\ffailureCount\x12&\n" +
	"\x0fnext_attempt_at\x18\x03 \x01(\tR\rnextAttemptAt\x12?\n" +
	"\bEnvelope\x18\x0f \x01(\v2#.dogma.interop.v1.envelope.EnvelopeR\bEnvelopeJ\x04\b\x04\x10\x0fBDZBgithub.com/dogmatiq/verity/persistence/boltpersistence/internal/pbb\x06proto3"

var (
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDescData []byte
)

func file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDesc), len(file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDescData
}

var file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_goTypes = []any{
	(*QueueMessage)(nil),          // 0: verity.persistence.boltdb.v1.QueueMessage
	(*envelopespec.Envelope)(nil), // 1: dogma.interop.v1.envelope.Envelope
}
var file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_depIdxs = []int32{
	1, // 0: verity.persistence.boltdb.v1.QueueMessage.Envelope:type_name -> dogma.interop.v1.envelope.Envelope
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_init()
}
func file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_init() {
	if File_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDesc), len(file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto = out.File
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_goTypes = nil
	file_github_com_dogmatiq_verity_persistence_boltpersistence_internal_pb_queue_proto_depIdxs = nil
}
