// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/draftspecs/messagingspec/queue.proto

package messagingspec

import (
	context "context"
	fmt "fmt"
	envelopespec "github.com/dogmatiq/infix/internal/draftspecs/envelopespec"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnqueueRequest struct {
	// ApplicationKey is the identity key of the application that handles the
	// command.
	ApplicationKey string `protobuf:"bytes,1,opt,name=application_key,json=applicationKey,proto3" json:"application_key,omitempty"`
	// Envelope is the envelope containing the command to be executed.
	Envelope             *envelopespec.Envelope `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EnqueueRequest) Reset()         { *m = EnqueueRequest{} }
func (m *EnqueueRequest) String() string { return proto.CompactTextString(m) }
func (*EnqueueRequest) ProtoMessage()    {}
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_060dee6d6bcf67d1, []int{0}
}

func (m *EnqueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueRequest.Unmarshal(m, b)
}
func (m *EnqueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueRequest.Marshal(b, m, deterministic)
}
func (m *EnqueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueRequest.Merge(m, src)
}
func (m *EnqueueRequest) XXX_Size() int {
	return xxx_messageInfo_EnqueueRequest.Size(m)
}
func (m *EnqueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueRequest proto.InternalMessageInfo

func (m *EnqueueRequest) GetApplicationKey() string {
	if m != nil {
		return m.ApplicationKey
	}
	return ""
}

func (m *EnqueueRequest) GetEnvelope() *envelopespec.Envelope {
	if m != nil {
		return m.Envelope
	}
	return nil
}

type EnqueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueResponse) Reset()         { *m = EnqueueResponse{} }
func (m *EnqueueResponse) String() string { return proto.CompactTextString(m) }
func (*EnqueueResponse) ProtoMessage()    {}
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_060dee6d6bcf67d1, []int{1}
}

func (m *EnqueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueResponse.Unmarshal(m, b)
}
func (m *EnqueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueResponse.Marshal(b, m, deterministic)
}
func (m *EnqueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueResponse.Merge(m, src)
}
func (m *EnqueueResponse) XXX_Size() int {
	return xxx_messageInfo_EnqueueResponse.Size(m)
}
func (m *EnqueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueResponse proto.InternalMessageInfo

type AckRequest struct {
	// ApplicationKey is the identity key of the application that produced the
	// command.
	ApplicationKey string `protobuf:"bytes,1,opt,name=application_key,json=applicationKey,proto3" json:"application_key,omitempty"`
	// MessageID is the command message's unique identifier.
	MessageId            string   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckRequest) Reset()         { *m = AckRequest{} }
func (m *AckRequest) String() string { return proto.CompactTextString(m) }
func (*AckRequest) ProtoMessage()    {}
func (*AckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_060dee6d6bcf67d1, []int{2}
}

func (m *AckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRequest.Unmarshal(m, b)
}
func (m *AckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRequest.Marshal(b, m, deterministic)
}
func (m *AckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRequest.Merge(m, src)
}
func (m *AckRequest) XXX_Size() int {
	return xxx_messageInfo_AckRequest.Size(m)
}
func (m *AckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AckRequest proto.InternalMessageInfo

func (m *AckRequest) GetApplicationKey() string {
	if m != nil {
		return m.ApplicationKey
	}
	return ""
}

func (m *AckRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

type AckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckResponse) Reset()         { *m = AckResponse{} }
func (m *AckResponse) String() string { return proto.CompactTextString(m) }
func (*AckResponse) ProtoMessage()    {}
func (*AckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_060dee6d6bcf67d1, []int{3}
}

func (m *AckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckResponse.Unmarshal(m, b)
}
func (m *AckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckResponse.Marshal(b, m, deterministic)
}
func (m *AckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckResponse.Merge(m, src)
}
func (m *AckResponse) XXX_Size() int {
	return xxx_messageInfo_AckResponse.Size(m)
}
func (m *AckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EnqueueRequest)(nil), "dogma.messaging.v1.EnqueueRequest")
	proto.RegisterType((*EnqueueResponse)(nil), "dogma.messaging.v1.EnqueueResponse")
	proto.RegisterType((*AckRequest)(nil), "dogma.messaging.v1.AckRequest")
	proto.RegisterType((*AckResponse)(nil), "dogma.messaging.v1.AckResponse")
}

func init() {
	proto.RegisterFile("internal/draftspecs/messagingspec/queue.proto", fileDescriptor_060dee6d6bcf67d1)
}

var fileDescriptor_060dee6d6bcf67d1 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0x3a, 0x31,
	0x10, 0xc5, 0xb3, 0xff, 0x7f, 0xa2, 0x32, 0x28, 0xc4, 0x9e, 0x08, 0x46, 0x25, 0xeb, 0x41, 0x2e,
	0xb6, 0x01, 0x0f, 0x1e, 0x8c, 0x07, 0x34, 0x98, 0x18, 0x4f, 0x6e, 0x3c, 0x79, 0x21, 0x65, 0x77,
	0x58, 0x1b, 0xd8, 0xb6, 0x6c, 0xbb, 0x44, 0xbe, 0x92, 0x9f, 0xd2, 0xd0, 0x2e, 0xab, 0x46, 0xd4,
	0x78, 0xeb, 0x4c, 0x5f, 0x7e, 0xef, 0xcd, 0xb4, 0x70, 0x26, 0xa4, 0xc5, 0x5c, 0xf2, 0x19, 0x4b,
	0x72, 0x3e, 0xb1, 0x46, 0x63, 0x6c, 0x58, 0x86, 0xc6, 0xf0, 0x54, 0xc8, 0x74, 0x55, 0xb2, 0x79,
	0x81, 0x05, 0x52, 0x9d, 0x2b, 0xab, 0x08, 0x49, 0x54, 0x9a, 0x71, 0x5a, 0x09, 0xe8, 0xa2, 0xd7,
	0x66, 0x9b, 0x10, 0x28, 0x17, 0x38, 0x53, 0x1a, 0x1d, 0x61, 0x5d, 0x78, 0x48, 0x98, 0x43, 0x63,
	0x28, 0x1d, 0x35, 0xc2, 0x79, 0x81, 0xc6, 0x92, 0x53, 0x68, 0x72, 0xad, 0x67, 0x22, 0xe6, 0x56,
	0x28, 0x39, 0x9a, 0xe2, 0xb2, 0x15, 0x74, 0x82, 0x6e, 0x2d, 0x6a, 0x7c, 0x68, 0xdf, 0xe3, 0x92,
	0x5c, 0xc0, 0xce, 0x1a, 0xd6, 0xfa, 0xd7, 0x09, 0xba, 0xf5, 0xfe, 0x01, 0xf5, 0x91, 0x2a, 0x8f,
	0x45, 0x8f, 0x0e, 0xcb, 0x73, 0x54, 0x89, 0xc3, 0x7d, 0x68, 0x56, 0x9e, 0x46, 0x2b, 0x69, 0x30,
	0x7c, 0x04, 0x18, 0xc4, 0xd3, 0x3f, 0x47, 0x38, 0x04, 0xf0, 0xe3, 0xe3, 0x48, 0x24, 0x2e, 0x44,
	0x2d, 0xaa, 0x95, 0x9d, 0xbb, 0x24, 0xdc, 0x83, 0xba, 0xa3, 0x7a, 0x93, 0xfe, 0x6b, 0x00, 0xbb,
	0x37, 0x2a, 0xcb, 0xb8, 0x4c, 0x1e, 0x56, 0xee, 0x24, 0x82, 0xed, 0x32, 0x08, 0x09, 0xe9, 0xd7,
	0x6d, 0xd2, 0xcf, 0x9b, 0x69, 0x9f, 0xfc, 0xa8, 0xf1, 0x26, 0xe4, 0x16, 0xfe, 0x0f, 0xe2, 0x29,
	0x39, 0xda, 0xa4, 0x7d, 0x1f, 0xb1, 0x7d, 0xfc, 0xed, 0xbd, 0xe7, 0x5c, 0x5f, 0x3d, 0x5d, 0xa6,
	0xc2, 0x3e, 0x17, 0x63, 0x1a, 0xab, 0x8c, 0x39, 0xb1, 0x15, 0x73, 0x26, 0xe4, 0x44, 0xbc, 0xb0,
	0x5f, 0x3f, 0xca, 0x78, 0xcb, 0x3d, 0xef, 0xf9, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x8a,
	0x7e, 0xf7, 0x54, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommandQueueClient is the client API for CommandQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandQueueClient interface {
	// Enqueue adds a message to the inbound command queue.
	//
	// The client is an engine with a message on its outbound queue. The server is
	// an engine that hosts an application that can handle commands of that type.
	//
	// If the server does not host the application specified in the request, it
	// MUST return a NOT_FOUND error with an attached UnrecognizedApplication
	// value.
	//
	// If the server does not handle messages of the type provided in the request,
	// it MUST return an INVALID_ARGUMENT error with an attached
	// UnrecognizedMessage value.
	//
	// The server MUST keep the enqueued message on its inbound queue until it
	// removes the message from the client's outbound queue by calling Ack(). The
	// mechanism for determining how to dial back to the client is engine-specific
	// and outside the scope of this specification.
	//
	// If the message in the request, identified by the message ID, is not already
	// on the queue, it is added. A successful response MUST be returned
	// regardless of whether the message was already enqueued or not.
	//
	// The client SHOULD retry the Enqueue() oepration until it receives a
	// successful response, or until it receives an Ack() call for the message.
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	// Ack removes a message from the outbound command queue.
	//
	// The client is an engine that has enqueued (and potentially already
	// executed) a message received via a prior call to Enqueue().
	//
	// If the message specified in the request is still on the outbound queue, it
	// is removed. A successful response MUST be returned regardless of whether
	// the message was still enqueued or not.
	//
	// Upon returning a successful response, the server MUST NOT make any future
	// call to Enqueue() for the specified message.
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
}

type commandQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandQueueClient(cc grpc.ClientConnInterface) CommandQueueClient {
	return &commandQueueClient{cc}
}

func (c *commandQueueClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, "/dogma.messaging.v1.CommandQueue/Enqueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandQueueClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, "/dogma.messaging.v1.CommandQueue/Ack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandQueueServer is the server API for CommandQueue service.
type CommandQueueServer interface {
	// Enqueue adds a message to the inbound command queue.
	//
	// The client is an engine with a message on its outbound queue. The server is
	// an engine that hosts an application that can handle commands of that type.
	//
	// If the server does not host the application specified in the request, it
	// MUST return a NOT_FOUND error with an attached UnrecognizedApplication
	// value.
	//
	// If the server does not handle messages of the type provided in the request,
	// it MUST return an INVALID_ARGUMENT error with an attached
	// UnrecognizedMessage value.
	//
	// The server MUST keep the enqueued message on its inbound queue until it
	// removes the message from the client's outbound queue by calling Ack(). The
	// mechanism for determining how to dial back to the client is engine-specific
	// and outside the scope of this specification.
	//
	// If the message in the request, identified by the message ID, is not already
	// on the queue, it is added. A successful response MUST be returned
	// regardless of whether the message was already enqueued or not.
	//
	// The client SHOULD retry the Enqueue() oepration until it receives a
	// successful response, or until it receives an Ack() call for the message.
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	// Ack removes a message from the outbound command queue.
	//
	// The client is an engine that has enqueued (and potentially already
	// executed) a message received via a prior call to Enqueue().
	//
	// If the message specified in the request is still on the outbound queue, it
	// is removed. A successful response MUST be returned regardless of whether
	// the message was still enqueued or not.
	//
	// Upon returning a successful response, the server MUST NOT make any future
	// call to Enqueue() for the specified message.
	Ack(context.Context, *AckRequest) (*AckResponse, error)
}

// UnimplementedCommandQueueServer can be embedded to have forward compatible implementations.
type UnimplementedCommandQueueServer struct {
}

func (*UnimplementedCommandQueueServer) Enqueue(ctx context.Context, req *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enqueue not implemented")
}
func (*UnimplementedCommandQueueServer) Ack(ctx context.Context, req *AckRequest) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ack not implemented")
}

func RegisterCommandQueueServer(s *grpc.Server, srv CommandQueueServer) {
	s.RegisterService(&_CommandQueue_serviceDesc, srv)
}

func _CommandQueue_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandQueueServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogma.messaging.v1.CommandQueue/Enqueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandQueueServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandQueue_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandQueueServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogma.messaging.v1.CommandQueue/Ack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandQueueServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommandQueue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dogma.messaging.v1.CommandQueue",
	HandlerType: (*CommandQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _CommandQueue_Enqueue_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _CommandQueue_Ack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/draftspecs/messagingspec/queue.proto",
}
