// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/draftspecs/messagingspec/stream.proto

package messagingspec

import (
	context "context"
	fmt "fmt"
	envelopespec "github.com/dogmatiq/infix/internal/draftspecs/envelopespec"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumeRequest struct {
	// ApplicationKey is the identity key of the application to consume from.
	ApplicationKey string `protobuf:"bytes,1,opt,name=application_key,json=applicationKey,proto3" json:"application_key,omitempty"`
	// Offset is the offset of the earliest message to be consumed.
	//
	// The offset of the message returned will be greater than this value if the
	// event at that offset is one of the requested message types.
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// types is the set of message types to include in the results.
	Types                []string `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeRequest) Reset()         { *m = ConsumeRequest{} }
func (m *ConsumeRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumeRequest) ProtoMessage()    {}
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d929b4c81b2226e, []int{0}
}

func (m *ConsumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeRequest.Unmarshal(m, b)
}
func (m *ConsumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeRequest.Marshal(b, m, deterministic)
}
func (m *ConsumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeRequest.Merge(m, src)
}
func (m *ConsumeRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumeRequest.Size(m)
}
func (m *ConsumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeRequest proto.InternalMessageInfo

func (m *ConsumeRequest) GetApplicationKey() string {
	if m != nil {
		return m.ApplicationKey
	}
	return ""
}

func (m *ConsumeRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ConsumeRequest) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type ConsumeResponse struct {
	// Offset is the offset of the message.
	//
	// It will be greater than the offset provided in the ConsumeRequest if the
	// event at the requested offset was one fo the requested message types.
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Envelope is the envelope containing the event.
	Envelope             *envelopespec.Envelope `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConsumeResponse) Reset()         { *m = ConsumeResponse{} }
func (m *ConsumeResponse) String() string { return proto.CompactTextString(m) }
func (*ConsumeResponse) ProtoMessage()    {}
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d929b4c81b2226e, []int{1}
}

func (m *ConsumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeResponse.Unmarshal(m, b)
}
func (m *ConsumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeResponse.Marshal(b, m, deterministic)
}
func (m *ConsumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeResponse.Merge(m, src)
}
func (m *ConsumeResponse) XXX_Size() int {
	return xxx_messageInfo_ConsumeResponse.Size(m)
}
func (m *ConsumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeResponse proto.InternalMessageInfo

func (m *ConsumeResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ConsumeResponse) GetEnvelope() *envelopespec.Envelope {
	if m != nil {
		return m.Envelope
	}
	return nil
}

func init() {
	proto.RegisterType((*ConsumeRequest)(nil), "dogma.messaging.v1.ConsumeRequest")
	proto.RegisterType((*ConsumeResponse)(nil), "dogma.messaging.v1.ConsumeResponse")
}

func init() {
	proto.RegisterFile("internal/draftspecs/messagingspec/stream.proto", fileDescriptor_8d929b4c81b2226e)
}

var fileDescriptor_8d929b4c81b2226e = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x53, 0x51, 0x94, 0x62, 0x20, 0x69, 0x8c, 0x21, 0x78, 0x21, 0x78, 0x60, 0xa7, 0x56,
	0xd0, 0xc4, 0x83, 0xf1, 0xa2, 0xe1, 0x64, 0xbc, 0x4c, 0x4e, 0x5e, 0x4c, 0x81, 0xb7, 0xd9, 0xc8,
	0xda, 0xb2, 0x96, 0x45, 0xfe, 0x41, 0xff, 0x2e, 0x43, 0xbb, 0x2d, 0x23, 0x12, 0x77, 0xdb, 0xb7,
	0x7c, 0xef, 0xf7, 0xf5, 0x7d, 0x0f, 0x53, 0x21, 0x2d, 0xa4, 0x92, 0xaf, 0xd8, 0x32, 0xe5, 0x91,
	0x35, 0x1a, 0x16, 0x86, 0x25, 0x60, 0x0c, 0x8f, 0x85, 0x8c, 0x77, 0x92, 0x19, 0x9b, 0x02, 0x4f,
	0xa8, 0x4e, 0x95, 0x55, 0x84, 0x2c, 0x55, 0x9c, 0x70, 0x5a, 0x3a, 0x68, 0x36, 0xee, 0xb3, 0x43,
	0x0c, 0x90, 0x19, 0xac, 0x94, 0x06, 0x87, 0x28, 0x84, 0x87, 0xf4, 0xef, 0xea, 0x43, 0xbd, 0x02,
	0xbb, 0xd5, 0x60, 0xfc, 0xd4, 0x30, 0xc6, 0x9d, 0x67, 0x25, 0xcd, 0x26, 0x81, 0x10, 0xd6, 0x1b,
	0x30, 0x96, 0x8c, 0x70, 0x97, 0x6b, 0xbd, 0x12, 0x0b, 0x6e, 0x85, 0x92, 0x1f, 0x5f, 0xb0, 0xed,
	0xa1, 0x01, 0x0a, 0x5a, 0x61, 0xa7, 0xf2, 0xfb, 0x05, 0xb6, 0xe4, 0x12, 0x37, 0x55, 0x14, 0x19,
	0xb0, 0xbd, 0xa3, 0x01, 0x0a, 0x8e, 0xc3, 0x5c, 0x91, 0x0b, 0x7c, 0xe2, 0x12, 0x7a, 0x8d, 0x41,
	0x23, 0x68, 0x85, 0x5e, 0x0c, 0xe7, 0xb8, 0x5b, 0x06, 0x19, 0xad, 0xa4, 0x81, 0x0a, 0x00, 0xed,
	0x01, 0xee, 0xf1, 0x59, 0xb1, 0x9b, 0x43, 0xb7, 0x27, 0x57, 0xd4, 0x37, 0x54, 0xae, 0x9c, 0x8d,
	0xe9, 0x34, 0xff, 0x0e, 0x4b, 0xf3, 0xe4, 0x07, 0xe1, 0xf6, 0x34, 0x03, 0x69, 0xdf, 0x5c, 0xbb,
	0x64, 0x86, 0x4f, 0xf3, 0x4c, 0x32, 0xa4, 0x7f, 0x3b, 0xa6, 0xfb, 0x9b, 0xf7, 0xaf, 0xff, 0xf5,
	0xf8, 0x47, 0xdf, 0x20, 0xc2, 0xf1, 0xf9, 0xab, 0x2f, 0x72, 0xb6, 0xdb, 0x8c, 0x8c, 0x0e, 0x8d,
	0x55, 0x1d, 0x05, 0x3f, 0xa8, 0x37, 0xfa, 0x90, 0xa7, 0xc7, 0xf7, 0x87, 0x58, 0xd8, 0xcf, 0xcd,
	0x9c, 0x2e, 0x54, 0xc2, 0xdc, 0x94, 0x15, 0x6b, 0x26, 0x64, 0x24, 0xbe, 0x59, 0xed, 0x9d, 0xe7,
	0x4d, 0x77, 0xdb, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x11, 0x08, 0x6c, 0x88, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventStreamClient is the client API for EventStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventStreamClient interface {
	// Consume starts consuming from an application's event stream.
	//
	// If the server does not host the application specified in the request, it
	// MUST return a NOT_FOUND error with an attached UnrecognizedApplication
	// value.
	//
	// If the requested offset is beyond the end of the application's event
	// stream, the server SHOULD keep the stream open, sending the messages as
	// they become available.
	//
	// If any of the message types are not produced by the specified application
	// the server MUST return an INVALID_ARGUMENT error with an attached
	// UnrecognizedMessage value for each unrecognized message type.
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (EventStream_ConsumeClient, error)
	// MessageTypes queries the messages types that the server supports for a
	// specific application.
	//
	// If the server does not host the application specified in the request, it
	// MUST return a NOT_FOUND error with an attached UnrecognizedApplication
	// value.
	MessageTypes(ctx context.Context, in *MessageTypesRequest, opts ...grpc.CallOption) (*MessageTypesResponse, error)
}

type eventStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamClient(cc grpc.ClientConnInterface) EventStreamClient {
	return &eventStreamClient{cc}
}

func (c *eventStreamClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (EventStream_ConsumeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EventStream_serviceDesc.Streams[0], "/dogma.messaging.v1.EventStream/Consume", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventStreamConsumeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventStream_ConsumeClient interface {
	Recv() (*ConsumeResponse, error)
	grpc.ClientStream
}

type eventStreamConsumeClient struct {
	grpc.ClientStream
}

func (x *eventStreamConsumeClient) Recv() (*ConsumeResponse, error) {
	m := new(ConsumeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventStreamClient) MessageTypes(ctx context.Context, in *MessageTypesRequest, opts ...grpc.CallOption) (*MessageTypesResponse, error) {
	out := new(MessageTypesResponse)
	err := c.cc.Invoke(ctx, "/dogma.messaging.v1.EventStream/MessageTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStreamServer is the server API for EventStream service.
type EventStreamServer interface {
	// Consume starts consuming from an application's event stream.
	//
	// If the server does not host the application specified in the request, it
	// MUST return a NOT_FOUND error with an attached UnrecognizedApplication
	// value.
	//
	// If the requested offset is beyond the end of the application's event
	// stream, the server SHOULD keep the stream open, sending the messages as
	// they become available.
	//
	// If any of the message types are not produced by the specified application
	// the server MUST return an INVALID_ARGUMENT error with an attached
	// UnrecognizedMessage value for each unrecognized message type.
	Consume(*ConsumeRequest, EventStream_ConsumeServer) error
	// MessageTypes queries the messages types that the server supports for a
	// specific application.
	//
	// If the server does not host the application specified in the request, it
	// MUST return a NOT_FOUND error with an attached UnrecognizedApplication
	// value.
	MessageTypes(context.Context, *MessageTypesRequest) (*MessageTypesResponse, error)
}

// UnimplementedEventStreamServer can be embedded to have forward compatible implementations.
type UnimplementedEventStreamServer struct {
}

func (*UnimplementedEventStreamServer) Consume(req *ConsumeRequest, srv EventStream_ConsumeServer) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (*UnimplementedEventStreamServer) MessageTypes(ctx context.Context, req *MessageTypesRequest) (*MessageTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageTypes not implemented")
}

func RegisterEventStreamServer(s *grpc.Server, srv EventStreamServer) {
	s.RegisterService(&_EventStream_serviceDesc, srv)
}

func _EventStream_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStreamServer).Consume(m, &eventStreamConsumeServer{stream})
}

type EventStream_ConsumeServer interface {
	Send(*ConsumeResponse) error
	grpc.ServerStream
}

type eventStreamConsumeServer struct {
	grpc.ServerStream
}

func (x *eventStreamConsumeServer) Send(m *ConsumeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EventStream_MessageTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStreamServer).MessageTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dogma.messaging.v1.EventStream/MessageTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStreamServer).MessageTypes(ctx, req.(*MessageTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dogma.messaging.v1.EventStream",
	HandlerType: (*EventStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MessageTypes",
			Handler:    _EventStream_MessageTypes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _EventStream_Consume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/draftspecs/messagingspec/stream.proto",
}
