// Code generated by protoc-gen-go. DO NOT EDIT.
// source: draftspecs/envelopespec/envelope.proto

package envelopespec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Identity is a protocol buffers representation of the configkit.Identity type.
type Identity struct {
	// Name is the entity's unique name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key is the entity's immutable, unique key.
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_291e8cfade150cd6, []int{0}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Source struct {
	// Application is the identity of the Dogma application that produced this
	// message.
	Application *Identity `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// Handler is the identity of the handler that produced the message. It is the
	// zero-value if the message was not produced by a handler.
	Handler *Identity `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	// InstanceID is the aggregate or process instance that produced the message.
	// It is empty if the message was not produced by a handler, or it was
	// produced by an integration handler.
	InstanceId           string   `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_291e8cfade150cd6, []int{1}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetApplication() *Identity {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *Source) GetHandler() *Identity {
	if m != nil {
		return m.Handler
	}
	return nil
}

func (m *Source) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

// MetaData is a protocol buffers representation of the envelope.MetaData type.
type MetaData struct {
	// MessageID is a unique identifier for the message.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// CausationID is the ID of the message that was being handled when the
	// message identified by MessageID was produced.
	CausationId string `protobuf:"bytes,2,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	// CorrelationID is the ID of the "root" message that entered the application
	// to cause the message identified by MessageID, either directly or
	// indirectly.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Source describes the source of the message.
	Source *Source `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// CreatedAt is the time at which the message was created, marshaled in
	// binary format.
	CreatedAt []byte `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ScheduledFor is the time at which a timeout message was scheduled,
	// marshaled in binary format.
	ScheduledFor         []byte   `protobuf:"bytes,6,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaData) Reset()         { *m = MetaData{} }
func (m *MetaData) String() string { return proto.CompactTextString(m) }
func (*MetaData) ProtoMessage()    {}
func (*MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_291e8cfade150cd6, []int{2}
}

func (m *MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaData.Unmarshal(m, b)
}
func (m *MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaData.Marshal(b, m, deterministic)
}
func (m *MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaData.Merge(m, src)
}
func (m *MetaData) XXX_Size() int {
	return xxx_messageInfo_MetaData.Size(m)
}
func (m *MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MetaData proto.InternalMessageInfo

func (m *MetaData) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *MetaData) GetCausationId() string {
	if m != nil {
		return m.CausationId
	}
	return ""
}

func (m *MetaData) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *MetaData) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MetaData) GetCreatedAt() []byte {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *MetaData) GetScheduledFor() []byte {
	if m != nil {
		return m.ScheduledFor
	}
	return nil
}

// Envelope is a protocol buffers representation of the envelope.Envelope type.
type Envelope struct {
	// MetaData is the message meta-data.
	MetaData *MetaData `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	// PortableName is the unique name used to identify messages of this type.
	PortableName string `protobuf:"bytes,2,opt,name=portable_name,json=portableName,proto3" json:"portable_name,omitempty"`
	// MediaType is a MIME media-type describing the content and encoding of the
	// binary message data.
	MediaType string `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// Data is the binary message data.
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_291e8cfade150cd6, []int{3}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetMetaData() *MetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *Envelope) GetPortableName() string {
	if m != nil {
		return m.PortableName
	}
	return ""
}

func (m *Envelope) GetMediaType() string {
	if m != nil {
		return m.MediaType
	}
	return ""
}

func (m *Envelope) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Identity)(nil), "dogma.envelope.v1.Identity")
	proto.RegisterType((*Source)(nil), "dogma.envelope.v1.Source")
	proto.RegisterType((*MetaData)(nil), "dogma.envelope.v1.MetaData")
	proto.RegisterType((*Envelope)(nil), "dogma.envelope.v1.Envelope")
}

func init() {
	proto.RegisterFile("draftspecs/envelopespec/envelope.proto", fileDescriptor_291e8cfade150cd6)
}

var fileDescriptor_291e8cfade150cd6 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0xab, 0xd3, 0x40,
	0x14, 0xc5, 0x89, 0xaf, 0xd6, 0xe6, 0xb6, 0x15, 0x9d, 0x55, 0x44, 0xc4, 0x67, 0x1f, 0xca, 0x5b,
	0xa5, 0xd6, 0x87, 0xe0, 0xc6, 0x85, 0xa2, 0x42, 0x16, 0xba, 0x88, 0xae, 0xdc, 0x84, 0xdb, 0x99,
	0xdb, 0x76, 0x30, 0xc9, 0xc4, 0xc9, 0xed, 0xc3, 0x7c, 0x17, 0xc1, 0xef, 0xe7, 0xa7, 0x90, 0xdc,
	0xfc, 0xa1, 0xe0, 0xbf, 0xdd, 0xcc, 0x8f, 0x33, 0xb9, 0xe7, 0x9e, 0x1c, 0x78, 0x62, 0x3c, 0xee,
	0xb8, 0xae, 0x48, 0xd7, 0x6b, 0x2a, 0xaf, 0x29, 0x77, 0x15, 0xb5, 0xb7, 0xf1, 0x12, 0x57, 0xde,
	0xb1, 0x53, 0x77, 0x8d, 0xdb, 0x17, 0x18, 0x8f, 0xf4, 0x7a, 0xb3, 0x7a, 0x0a, 0xb3, 0xc4, 0x50,
	0xc9, 0x96, 0x1b, 0xa5, 0x60, 0x52, 0x62, 0x41, 0x51, 0x70, 0x1e, 0x5c, 0x86, 0xa9, 0x9c, 0xd5,
	0x1d, 0x38, 0xfb, 0x42, 0x4d, 0x74, 0x43, 0x50, 0x7b, 0x5c, 0xfd, 0x08, 0x60, 0xfa, 0xd1, 0x1d,
	0xbd, 0x26, 0xf5, 0x12, 0xe6, 0x58, 0x55, 0xb9, 0xd5, 0xc8, 0xd6, 0x95, 0xf2, 0x6e, 0xfe, 0xec,
	0x7e, 0xfc, 0xdb, 0x94, 0x78, 0x18, 0x91, 0x9e, 0xea, 0xd5, 0x73, 0xb8, 0x75, 0xc0, 0xd2, 0xe4,
	0xe4, 0xe5, 0xfb, 0xff, 0x79, 0x3a, 0x68, 0xd5, 0x43, 0x98, 0xdb, 0xb2, 0x66, 0x2c, 0x35, 0x65,
	0xd6, 0x44, 0x67, 0x62, 0x0d, 0x06, 0x94, 0x98, 0xd5, 0xcf, 0x00, 0x66, 0xef, 0x89, 0xf1, 0x0d,
	0x32, 0xaa, 0x07, 0x00, 0x05, 0xd5, 0x35, 0xee, 0x45, 0xdc, 0xad, 0x16, 0xf6, 0x24, 0x31, 0xea,
	0x11, 0x2c, 0x34, 0x1e, 0x6b, 0x31, 0xd4, 0x0a, 0xba, 0x45, 0xe7, 0x23, 0x4b, 0x8c, 0x7a, 0x0c,
	0xb7, 0xb5, 0xf3, 0x9e, 0xf2, 0x51, 0xd4, 0x8d, 0x5c, 0x9e, 0xd0, 0xc4, 0xa8, 0x0d, 0x4c, 0x6b,
	0x89, 0x25, 0x9a, 0xc8, 0x32, 0xf7, 0xfe, 0xb0, 0x4c, 0x97, 0x5b, 0xda, 0x0b, 0x5b, 0x6f, 0xda,
	0x13, 0x32, 0x99, 0x0c, 0x39, 0xba, 0x79, 0x1e, 0x5c, 0x2e, 0xd2, 0xb0, 0x27, 0xaf, 0x58, 0x5d,
	0xc0, 0xb2, 0xd6, 0x07, 0x32, 0xc7, 0x9c, 0x4c, 0xb6, 0x73, 0x3e, 0x9a, 0x8a, 0x62, 0x31, 0xc2,
	0x77, 0xce, 0xaf, 0xbe, 0x07, 0x30, 0x7b, 0xdb, 0x8f, 0x50, 0x2f, 0x20, 0x2c, 0x88, 0x31, 0x33,
	0xc8, 0xf8, 0x8f, 0xdf, 0x31, 0x84, 0x93, 0xce, 0x8a, 0x21, 0xa6, 0x0b, 0x58, 0x56, 0xce, 0x33,
	0x6e, 0x73, 0xca, 0xa4, 0x04, 0x5d, 0x10, 0x8b, 0x01, 0x7e, 0x68, 0xcb, 0x20, 0x59, 0x1a, 0x8b,
	0x19, 0x37, 0x15, 0xf5, 0x29, 0x84, 0x42, 0x3e, 0x35, 0x15, 0xb5, 0xfd, 0x91, 0xc1, 0x13, 0xb1,
	0x29, 0xe7, 0xd7, 0x57, 0x9f, 0x37, 0x7b, 0xcb, 0x87, 0xe3, 0x36, 0xd6, 0xae, 0x58, 0x8b, 0x15,
	0xb6, 0x5f, 0xd7, 0xb6, 0xdc, 0xd9, 0x6f, 0xeb, 0xbf, 0xd4, 0x76, 0x3b, 0x95, 0xba, 0x5e, 0xfd,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xd3, 0x4b, 0xc9, 0xd8, 0x02, 0x00, 0x00,
}
